CITIES_1 = [
    "Atlanta",
    "Austin",
    "Baltimore",
    "Boston",
    "Buffalo",
    "Charlotte",
    "Chicago",
    "Cincinnati",
    "Cleveland",
    "Columbus",
    "Dallas",
    "Denver",
    "Detroit",
    "Houston",
    "Indianapolis",
    "Jacksonville",
    "Louisville",
    "Memphis",
    "Miami",
    "Milwaukee",
    "Minneapolis",
    "Nashville",
    "Oakland",
    "Orlando",
    "Philadelphia",
    "Phoenix",
    "Pittsburgh",
    "Portland",
    "Sacramento",
    "Seattle",
    "Tampa",
    "Tucson",
    "Albuquerque",
    "Anchorage",
    "Anaheim",
    "Arlington",
    "Aurora",
    "Bakersfield",
    "Birmingham",
    "Boise",
    "Chandler",
    "Chesapeake",
    "Chula",
    "Corpus",
    "Durham",
    "Erie",
    "Fargo",
    "Fresno",
    "Garland",
    "Gilbert",
    "Glendale",
    "Henderson",
    "Hialeah",
    "Honolulu",
    "Irving",
    "Jersey",
    "Knoxville",
    "Laredo",
    "Lexington",
    "Lincoln",
    "Lubbock",
    "Madison",
    "Mesa",
    "Montgomery",
    "Newark",
    "Norfolk",
    "Oakland",
    "Omaha",
    "Orlando",
    "Plano",
    "Raleigh",
    "Reno",
    "Richmond",
    "Rochester",
    "Salem",
    "Scottsdale",
    "Shreveport",
    "Spokane",
    "Springfield",
    "Stockton",
    "Syracuse",
    "Tacoma",
    "Toledo",
    "Tulsa",
    "Waco",
    "Wichita",
    "Winston",
    "Boulder",
    "Burlington",
    "Cambridge",
    "Eugene",
    "Evansville",
    "Flint",
    "Gainesville",
    "Hartford",
    "Hollywood",
    "Huntsville",
    "Jackson",
    "Lansing",
    "Providence"
]

CITIES = [
    "Atlanta",
    "Austin",
    "Boston"
]

CITIES_STATES = [
    "Atlanta, Georgia",
    "Austin, Texas",
    "Baltimore, Maryland",
    "Boston, Massachusetts",
    "Buffalo, New York",
    "Charlotte, North Carolina",
    "Chicago, Illinois",
    "Cincinnati, Ohio",
    "Cleveland, Ohio",
    "Columbus, Ohio",
    "Dallas, Texas",
    "Denver, Colorado",
    "Detroit, Michigan",
    "Houston, Texas",
    "Indianapolis, Indiana",
    "Jacksonville, Florida",
    "Louisville, Kentucky",
    "Memphis, Tennessee",
    "Miami, Florida",
    "Milwaukee, Wisconsin",
    "Minneapolis, Minnesota",
    "Nashville, Tennessee",
    "Oakland, California",
    "Orlando, Florida",
    "Philadelphia, Pennsylvania",
    "Phoenix, Arizona",
    "Pittsburgh, Pennsylvania",
    "Portland, Oregon",
    "Sacramento, California",
    "Seattle, Washington",
    "Tampa, Florida",
    "Tucson, Arizona",
    "Albuquerque, New Mexico",
    "Anchorage, Alaska",
    "Anaheim, California",
    "Arlington, Texas",
    "Aurora, Colorado",
    "Bakersfield, California",
    "Birmingham, Alabama",
    "Boise, Idaho",
    "Chandler, Arizona",
    "Chesapeake, Virginia",
    "Chula Vista, California",
    "Corpus Christi, Texas",
    "Durham, North Carolina",
    "Erie, Pennsylvania",
    "Fargo, North Dakota",
    "Fresno, California",
    "Garland, Texas",
    "Gilbert, Arizona",
    "Glendale, Arizona",
    "Henderson, Nevada",
    "Hialeah, Florida",
    "Honolulu, Hawaii",
    "Irving, Texas",
    "Jersey City, New Jersey",
    "Knoxville, Tennessee",
    "Laredo, Texas",
    "Lexington, Kentucky",
    "Lincoln, Nebraska",
    "Lubbock, Texas",
    "Madison, Wisconsin",
    "Mesa, Arizona",
    "Montgomery, Alabama",
    "Newark, New Jersey",
    "Norfolk, Virginia",
    "Oakland, California",
    "Omaha, Nebraska",
    "Orlando, Florida",
    "Plano, Texas",
    "Raleigh, North Carolina",
    "Reno, Nevada",
    "Richmond, Virginia",
    "Rochester, New York",
    "Salem, Oregon",
    "Scottsdale, Arizona",
    "Shreveport, Louisiana",
    "Spokane, Washington",
    "Springfield, Missouri",
    "Stockton, California",
    "Syracuse, New York",
    "Tacoma, Washington",
    "Toledo, Ohio",
    "Tulsa, Oklahoma",
    "Waco, Texas",
    "Wichita, Kansas",
    "Winston-Salem, North Carolina",
    "Boulder, Colorado",
    "Burlington, Vermont",
    "Cambridge, Massachusetts",
    "Eugene, Oregon",
    "Evansville, Indiana",
    "Flint, Michigan",
    "Gainesville, Florida",
    "Hartford, Connecticut",
    "Hollywood, Florida",
    "Huntsville, Alabama",
    "Jackson, Mississippi",
    "Lansing, Michigan",
    "Providence, Rhode Island"
]

# Dictionary format alternative if you need to separate city and state
CITIES_DICT = {
    "Atlanta": "Georgia",
    "Austin": "Texas",
    "Baltimore": "Maryland",
    "Boston": "Massachusetts",
    "Buffalo": "New York",
    "Charlotte": "North Carolina",
    "Chicago": "Illinois",
    "Cincinnati": "Ohio",
    "Cleveland": "Ohio",
    "Columbus": "Ohio",
    "Dallas": "Texas",
    "Denver": "Colorado",
    "Detroit": "Michigan",
    "Houston": "Texas",
    "Indianapolis": "Indiana",
    "Jacksonville": "Florida",
    "Louisville": "Kentucky",
    "Memphis": "Tennessee",
    "Miami": "Florida",
    "Milwaukee": "Wisconsin",
    "Minneapolis": "Minnesota",
    "Nashville": "Tennessee",
    "Oakland": "California",
    "Orlando": "Florida",
    "Philadelphia": "Pennsylvania",
    "Phoenix": "Arizona",
    "Pittsburgh": "Pennsylvania",
    "Portland": "Oregon",
    "Sacramento": "California",
    "Seattle": "Washington",
    "Tampa": "Florida",
    "Tucson": "Arizona",
    "Albuquerque": "New Mexico",
    "Anchorage": "Alaska",
    "Anaheim": "California",
    "Arlington": "Texas",
    "Aurora": "Colorado",
    "Bakersfield": "California",
    "Birmingham": "Alabama",
    "Boise": "Idaho",
    "Chandler": "Arizona",
    "Chesapeake": "Virginia",
    "Chula Vista": "California",
    "Corpus Christi": "Texas",
    "Durham": "North Carolina",
    "Erie": "Pennsylvania",
    "Fargo": "North Dakota",
    "Fresno": "California",
    "Garland": "Texas",
    "Gilbert": "Arizona",
    "Glendale": "Arizona",
    "Henderson": "Nevada",
    "Hialeah": "Florida",
    "Honolulu": "Hawaii",
    "Irving": "Texas",
    "Jersey City": "New Jersey",
    "Knoxville": "Tennessee",
    "Laredo": "Texas",
    "Lexington": "Kentucky",
    "Lincoln": "Nebraska",
    "Lubbock": "Texas",
    "Madison": "Wisconsin",
    "Mesa": "Arizona",
    "Montgomery": "Alabama",
    "Newark": "New Jersey",
    "Norfolk": "Virginia",
    "Oakland": "California",
    "Omaha": "Nebraska",
    "Orlando": "Florida",
    "Plano": "Texas",
    "Raleigh": "North Carolina",
    "Reno": "Nevada",
    "Richmond": "Virginia",
    "Rochester": "New York",
    "Salem": "Oregon",
    "Scottsdale": "Arizona",
    "Shreveport": "Louisiana",
    "Spokane": "Washington",
    "Springfield": "Missouri",
    "Stockton": "California",
    "Syracuse": "New York",
    "Tacoma": "Washington",
    "Toledo": "Ohio",
    "Tulsa": "Oklahoma",
    "Waco": "Texas",
    "Wichita": "Kansas",
    "Winston-Salem": "North Carolina",
    "Boulder": "Colorado",
    "Burlington": "Vermont",
    "Cambridge": "Massachusetts",
    "Eugene": "Oregon",
    "Evansville": "Indiana",
    "Flint": "Michigan",
    "Gainesville": "Florida",
    "Hartford": "Connecticut",
    "Hollywood": "Florida",
    "Huntsville": "Alabama",
    "Jackson": "Mississippi",
    "Lansing": "Michigan",
    "Providence": "Rhode Island"
}