name: 'Build and Deploy to Cloud Run'

on:
  push:
    branches:
      - main  # Or whichever branch you deploy from

env:
  PROJECT_ID: 'bda-project-server-455505'
  REGION: 'us-central1'
  SERVICE: 'sqs-backend'
  GAR_NAME: 'cloud-run-source-deploy'

jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'
      
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
          token_format: 'access_token'

      - name: 'Docker Auth'        
        run: |-
          gcloud auth configure-docker "${{ env.REGION }}-docker.pkg.dev"
          
      - name: 'Build and Push Container'
        run: |-
          DOCKER_TAG="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_NAME }}/${{ env.SERVICE }}:${{ github.sha }}"
          docker build --tag "${DOCKER_TAG}" .
          docker push "${DOCKER_TAG}"
          
      - name: 'Deploy to Cloud Run'
        id: deploy
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: '${{ env.SERVICE }}'
          region: '${{ env.REGION }}'
          image: "${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_NAME }}/${{ env.SERVICE }}:${{ github.sha }}"
          
      - name: 'Show Service URL'
        run: echo "Service URL: ${{ steps.deploy.outputs.url }}"